function showInfo(developer) {
	const developerName = document.getElementById('developer-name');
	const developerDescription = document.getElementById('developer-description');
	const developerImage = document.getElementById('developer-image');

	if (developer === 'Susan') {
		developerName.textContent = 'Susan Muñoz (Fundadora)';
		developerDescription.innerHTML =
			'Hola, soy Susan Muñoz. <br />Soy Odontopediatra con 10 años de experiencia y me considero una mujer emprendedora, con una profunda vocación de servicio y con un propósito firme de aportar valor a través de lo que hago. <br><br>Me encantan los niños y aprender de ellos, soy mamá de 3 (8 años, 2 años y 1 año). Me gusta viajar y conocer nuevas culturas, gracias a eso he tenido la oportunidad con mi familia de vivir en distintos países como Venezuela, Argentina y actualmente Costa Rica. En mi travesía  en la parte profesional he podido notar que los problemas de salud bucal coinciden.<br><br>Durante estos 10 años he trabajado promoviendo la importancia de la salud bucal como parte de la salud general a través de Chikident.<br><br>Me siento muy agradecida, procuro siempre vivir la vida con una perspectiva de crecimiento y disfrute de nuevas oportunidades. Siento que haber coincidido con Dani y Mari para éste proyecto es sólo el comienzo de un gran legado del que nos gustaría ser parte.<br><br>Conoce un poco de mi experiencia curricular:<br><br>Odontólogo. Graduada en la Universidad del Zulia (Venezuela) y la Universidad Nacional de Rosario (Argentina).<br><br>Especialista en Odontopediatría. Graduada en la Universidad del Salvador (Argentina).<br><br>Diplomado en Odontología para Bebés ILECCE (México).<br><br>Diplomado en Ortopedia Funcional de los Maxilares - SVOFM (Venezuela).';
		developerImage.src = './Images/27.png'; // Cambia por la ruta correcta de la imagen de Genesis
		developerImage.alt = 'Quality Assurance';
	} else if (developer === 'Daniela') {
		developerName.textContent = 'Daniela Figueroa (Fundadora)';
		developerDescription.innerHTML =
			'Hola soy Daniela. <br />Felizmente y con mucho orgullo puedo decir que soy esposa, madre de una bebé de 1 año y medio, hija y hermana de una familia muy auténtica. <br><br>Actualmente tengo más de 10 años como odontopediatra. Decidí estudiar odontología en la Universidad Central de Venezuela  y luego la especialidad en Odontopediatría en la universidad de Buenos Aires, siendo mi carrera y esta especialidad una de las cosas que más disfruto.<br><br>He vivido y trabajado en varios sitios del mundo como USA, Francia, Argentina y ahora en las Islas Baleares. Soy una persona que cree que hay que hacer cosas diferentes, donde la oportunidad es un factor clave para abrir nuevas puertas. Amo probar cosas nuevas, viajar, bailar flamenco, tomar vino, comer y disfrutar de las pequeñas cosas de la vida con familia, amigos y hasta sola.<br><br>Ayudar a los demás y aprender de ellos me llena el alma y el corazón.  Gracias a Mari, y Susan que en todo este tiempo hemos hecho un equipazo de ideas, anécdotas y experiencias que suman huellas en mi vida.<br><br>Conoce un poco de mi experiencia curricular:<br><br>Miembro de la SVOP (Sociedad Venezolana de Odontopediatría, y también de ALOP de la asociación latinoamericana de odontopediatría.<br><br>Especialista en Odontopediatría UBA(Argentina).<br><br>Diplomado en Argentina en ortopedia de los Maxilares AAOFM (Argentina).<br><br>Título de Odontología homologado en España.<br><br>Diplomado en Odontología para bebés. ILECCE (México).';
		developerImage.src = './Images/26.png'; // Cambia por la ruta correcta de la imagen de Dereck
		developerImage.alt = 'Programador';
	} else if (developer === 'Maria') {
		developerName.textContent = 'Maria Antonieta (Fundadora)';
		developerDescription.innerHTML =
			'Hola soy Odontólogo y Odontopediatra. <br />Graduada de la Universidad Santa Maria (USM), Caracas-Venezuela. Con 19 años de experiencia con especial enfoque en odontología para bebés desde ya hace más de 3 años. <br><br>Fundadora del Programa de Prevención Bucal Materno Infantil  en Caracas –Venezuela a través del cual empoderamos a los padres en salud bucal enseñando contenido avalado científicamente, realizando coaching desde la etapa prenatal a la dentición permanente. También soy miembro del Programa de Bebé Sin Caries en Caracas, donde realizamos chequeos preventivos a bebés. <br><br>Mamá de 2 hijos, (de  16 años y de 10 años) y esposa de un hombre maravilloso también Odontólogo y Cirujano Buco-Maxilofacial. Me considero una mujer valiente, emprendedora, muy luchadora y por sobre todo una mujer de Fe en Dios,  sin ella mi camino sería diferente. He tenido la oportunidad de vivir en USA, Europa, Centro América y Venezuela y cada experiencia vivida han sido usadas para moldearme , madurar, aprender de diferentes culturas e idiomas . <br><br>Conoce un poco de mi experiencia curricular:<br><br>Miembro SVOP y ALOP <br><br>Estomatólogo Integral del niño y adolescente USM -Caracas-Venezuela<br><br>Diplomado en Ortodoncia Interceptiva UCV -Caracas-Venezuela<br><br>Diplomado en Odontología para el bebé ILECCE México.<br><br>';
		developerImage.src = './Images/25.png'; // Cambia por la ruta correcta de la imagen de Dereck
		developerImage.alt = 'Programador';
	}
}
